### ISSUE TITLE
Laravel 5 compatibility

### ISSUE THREAD

**Issue by towel** [niterain/PhpTalView#3]
PhpTalView currently cannot be used with Laravel 5, which would be very nice.

    Problem 1
    - Installation request for niterain/php-tal-view dev-master -> satisfiable by niterain/php-tal-view[dev-master].
    - niterain/php-tal-view dev-master requires laravel/framework ~4.2.11 -> no matching package found.

**Comment by niterain** [comment]
Updated.

Could you test out the changes.
